/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'inverse-primary': '#b1c5ff',
        'surface-bright': '#fbf9f8',
        'on-background': '#1b1c1c',
        'on-secondary-container': '#785a1a',
        'on-primary-fixed-variant': '#224489',
        'on-secondary-fixed': '#261900',
        'secondary-fixed': '#ffdea5',
        'on-surface-variant': '#444651',
        tertiary: '#1a1d1e',
        'surface-container-highest': '#e4e2e2',
        'surface-dim': '#dbd9d9',
        'on-tertiary': '#ffffff',
        'on-tertiary-fixed': '#191c1d',
        'surface-tint': '#3d5ca2',
        'on-secondary': '#ffffff',
        'on-error-container': '#93000a',
        'on-primary-container': '#7a97e2',
        'tertiary-fixed-dim': '#c5c7c8',
        surface: '#fbf9f8',
        'on-tertiary-container': '#989a9b',
        'surface-variant': '#e4e2e2',
        'outline-variant': '#c4c6d2',
        'on-primary': '#ffffff',
        outline: '#747782',
        'inverse-surface': '#303030',
        'primary-fixed': '#dae2ff',
        secondary: '#775a19',
        'secondary-container': '#fed488',
        'on-secondary-fixed-variant': '#5d4201',
        'tertiary-fixed': '#e1e3e4',
        'surface-container-high': '#eae8e7',
        'primary-container': '#002d72',
        'error-container': '#ffdad6',
        'surface-container-low': '#f5f3f3',
        'secondary-fixed-dim': '#e9c176',
        primary: '#001a48',
        'inverse-on-surface': '#f2f0f0',
        'surface-container': '#efeded',
        'on-primary-fixed': '#001946',
        'on-surface': '#1b1c1c',
        'tertiary-container': '#2f3233',
        'primary-fixed-dim': '#b1c5ff',
        error: '#ba1a1a',
        'on-tertiary-fixed-variant': '#454748',
        'on-error': '#ffffff',
        background: '#fbf9f8',
        'surface-container-lowest': '#ffffff',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'margin-desktop': '64px',
        'margin-tablet': '40px',
        unit: '8px',
        'margin-mobile': '20px',
        gutter: '24px',
        'container-max': '1280px',
      },
      screens: {
        xs: '480px',
      },
      maxWidth: {
        'container-max': '1280px',
      },
      fontFamily: {
        'label-md': ['Work Sans', 'sans-serif'],
        'body-lg': ['Work Sans', 'sans-serif'],
        'body-md': ['Work Sans', 'sans-serif'],
        'headline-sm': ['Manrope', 'sans-serif'],
        'headline-md': ['Manrope', 'sans-serif'],
        'display-lg': ['Manrope', 'sans-serif'],
        'label-sm': ['Work Sans', 'sans-serif'],
        'display-lg-mobile': ['Manrope', 'sans-serif'],
      },
      fontSize: {
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.05em', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-sm': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-md': ['32px', { lineHeight: '40px', fontWeight: '600' }],
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '500' }],
        'display-lg-mobile': ['32px', { lineHeight: '40px', fontWeight: '700' }],
      },
    },
  },
  plugins: [require('@tailwindcss/forms')],
}
